apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  annotations:
    metallb.universe.tf/address-pool: single-ip
spec:
  ports:
  - name: grafana
    port: 3030
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: service_grafana
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        name: grafana

