apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: service_php-my-admin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: php-my-admin
data:
  config.inc.php: |
    <?php
    /**
     * phpMyAdmin sample configuration, you can use it as base for
     * manual configuration. For easier setup you can use setup/
     *
     * All directives are explained in documentation in the doc/ folder
     * or at <https://docs.phpmyadmin.net/>.
     *
    * @package PhpMyAdmin
     */

    /**
     * This is needed for cookie based authentication to encrypt password in
     * cookie. Needs to be 32 chars long.
     */
    $cfg['blowfish_secret'] = '01234567890123456789012345678912'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

    /**
     * Servers configuration
     */
    $i = 0;

    /**
     * First server
     */
    $i++;

    /* Authentication type */
    $cfg['Servers'][$i]['auth_type'] = 'cookie';

    /* Server parameters */
    $cfg['Servers'][$i]['host'] = 'mysql';
    $cfg['Servers'][$i]['port'] = '3306';
    $cfg['Servers'][$i]['user'] = 'admin';
    $cfg['Servers'][$i]['password'] = 'password';
    $cfg['Servers'][$i]['compress'] = 'false';
    $cfg['Servers'][$i]['AllowNoPassword'] = 'true';

    /**
     * Directories for saving/loading files from server
     */
    $cfg['UploadDir'] = '';
    $cfg['SaveDir'] = '';
    $cfg['PmaAbsoluteUri'] = '/phpmyadmin/';

